name: Build and publish binary and source packages

on:
  push:
    branches:
      - source
  workflow_dispatch:

jobs:
  merge:
    uses: ./.github/workflows/merge.yml

  build:
    needs: merge
    if: ${{ needs.merge.outputs.changed }}
    strategy:
      matrix:
        path: ${{ fromJson(needs.merge.outputs.changed) }}
      max-parallel: 1
    uses: ./.github/workflows/build-package.yml
    with:
      path: ${{ matrix.path }}

  delete:
    needs: merge
    if: ${{ needs.merge.outputs.deleted }}
    strategy:
      matrix:
        path: ${{ fromJson(needs.merge.outputs.deleted) }}
      max-parallel: 1
    uses: ./.github/workflows/delete-package.yml
    with:
      path: ${{ matrix.path }}

  publish:
    needs: [build, delete]
    if: always() && (needs.build.result == 'success' || needs.delete.result == 'success')
    uses: ./.github/workflows/publish.yml
