name: Publish binary and source packages

on:
  workflow_call:
    secrets:
      PGP_PRIVATE_KEY:
        required: true
  workflow_dispatch:
    secrets:
      PGP_PRIVATE_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: master

      - name: Install tools
        run: |
          sudo apt-get -y install --no-install-recommends apt-utils gpg
          echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --batch --import

      - name: Update source indices
        id: update
        run: |
          for d in dists/*; do
            [ -L $d ] && continue || sources=$d/main/source/Sources

            apt-ftparchive sources pool/main > $sources
            gzip -9c $sources > ${sources}.gz
          done

      - name: Update package indices
        run: |
          for d in dists/*; do
            [ -L $d ] && continue || suite=$(echo $d | cut -d/ -f2)

            for packages in dists/$suite/main/binary-*/Packages; do
              arch=$(echo $packages | cut -d/ -f4 | cut -d- -f2)

              for path in pool/main/*/$suite; do
                [ -e $path ] || continue

                apt-ftparchive packages --arch $arch $path
              done > $packages
              gzip -9c $packages > ${packages}.gz

            done
          done

      - name: Create release file
        run: |
          for d in dists/*; do
            [ -L $d ] && continue || suite=$(echo $d | cut -d/ -f2)
            
            cat >/tmp/arch.conf <<EOF
          APT::FTPArchive::Release {
            Origin "CCCP Linux";
            Suite "$suite";
            Codename "$suite";
          };
          EOF
            apt-ftparchive -c /tmp/arch.conf release $d > $d/Release

            gpg --batch --yes --detach-sign --armor -o $d/Release.gpg $d/Release
            gpg --batch --yes --clearsign -o $d/InRelease $d/Release
          done

      - name: Publish packages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dists/
          git commit -m "Update package metadata"
          git push origin master
