name: Delete binary package

on:
  workflow_call:
    inputs:
      path: { type: string }
  workflow_dispatch:
    inputs:
      path: { type: string }

permissions:
  contents: write

jobs:
  remove:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out master
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: master

      - name: Remove artifacts
        run: |
          name=$(basename ${{ inputs.path }} .dsc)
          vers=${name#*_}
          pool=$(dirname ${{ inputs.path }})

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm -rf $pool/*/*_${vers}_*
          git commit -m "Remove $name build artifacts"
          git push origin master
